#!/usr/bin/env sh

# If refreshing bspwm, remove all previous rules to prevent doubling up.
bspc rule -r "*"

if [ "$(hostname)" = "garry" ] && xrandr --query | grep "HDMI-0 connected"; then
    bspc monitor 'eDP-1-1' --remove
    bspc config pointer_motion_interval 7
fi

if [ "$(hostname)" = "liselle" ]; then
    bspc monitor 'HDMI-0' -d 1 2 3 4 5
    bspc monitor 'DVI-D-0' -d 6 7 8 9 10
elif [ "$(hostname)" = "halley" ] && xrandr --query | grep "HDMI-1 connected"; then
    bspc monitor 'HDMI-1' -d 1 2 3 4 5
    bspc monitor 'eDP-1' -d 6 7 8 9 10
else
    bspc monitor -d 1 2 3 4 5 6 7 8 9 10
fi

bspc config border_width 1
bspc config window_gap 0
# top_padding I set equal to polybar's height
bspc config top_padding 26

bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
bspc config pointer_follows_monitor true
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config removal_adjustment true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

bspc rule -a Debug desktop="2"
bspc rule -a Steam desktop="1"
bspc rule -a discord desktop="2"
bspc rule -a Spotify desktop="5"
bspc rule -a csgo_linux64 desktop="10"
