#!/usr/bin/env sh

killall -q sxhkd

sxhkd ~/.config/sxhkd/bspwm-sxhkdrc &

# If refreshing bspwm, remove all previous rules to prevent doubling up.
# bspc rule -r "*"

if [ "$(hostname)" = "halley" ]; then
    bspc monitor 'eDP1' -d 1 2 3 4 5 6 7 8 9 10
elif [ "$(hostname)" = "garry" ]; then
    bspc monitor 'HDMI-0' -d 1 2 3 4 5 6 7 8 9 10
elif [ "$(hostname)" = "liselle" ]; then
    bspc monitor 'HDMI-0' -d 1 2 3 4 5
    bspc monitor 'DVI-D-0' -d 6 7 8 9 10
else
    bspc monitor -d 1 2 3 4 5 6 7 8 9 10
fi
# bspc desktop -f 1

bspc config border_width 1
bspc config window_gap 0
# top_padding I set equal to polybar's height
bspc config top_padding 26

bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
bspc config pointer_follows_monitor true
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config removal_adjustment true
