#!/usr/bin/env sh

temp=$(nvidia-smi --query-gpu=temperature.gpu --format=csv,noheader)

if [ "$temp" -ge 100 ]; then
	color="#ff0000"
elif [ "$temp" -ge 94 ]; then
	color="#ffa500"
elif [ "$temp" -ge 70 ]; then
	color="#ffff00"
else
	color="#00ff00"
fi

LABEL="GPU🌡"
printf "<span color='%s'>%s%s°</span>\n" "$color" "$LABEL" "$temp"
