#!/usr/bin/env sh

case $BLOCK_BUTTON in
    1) notify-send "🧠 Memory hogs" "$(ps axch -o cmd:15,%mem --sort=-%mem | head)" ;;
    3) notify-send "🧠 Memory module" "\- Shows Memory Used/Total.
- Click to show memory hogs." ;;
esac

all=$(free -h | awk '/^Mem:/ {print $3 "/" $2}' | tr -d "G")
ratio=$(free | awk '/Mem/{printf("%.0f"), $3/$2*100}')

if [ "$ratio" -ge 75 ]; then
    color="#ff0000"
elif [ "$ratio" -ge 50 ]; then
    color="#ffa500"
elif [ "$ratio" -ge 25 ]; then
    color="#ffff00"
else
    color="#00ff00"
fi

printf "<span color='%s'>%s%%(%sG)</span>\n" "$color" "$ratio" "$all"
