#!/usr/bin/env sh

SINK=$(pactl list short sinks | sed -e 's,^\([0-9][0-9]*\)[^0-9].*,\1,' | head -n 1 || echo 0)
NOW=$(pactl list sinks | grep '^[[:space:]]Volume:' | head -n $((SINK + 1)) | tail -n 1 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,')
IS_MUTED=$(pactl list sinks | awk '/Mute/ { print $2 }' | head -n $((SINK + 1)) | tail -n 1)

LABEL=""
if [ "$IS_MUTED" = "yes" ]; then
    LABEL=""
fi

if [ "$NOW" -ge 75 ]; then
    color="#ffffff"
elif [ "$NOW" -ge 50 ]; then
    color="#00ff00"
elif [ "$NOW" -ge 25 ]; then
    color="#ffff00"
else
    color="#ffa500"
fi

if [ "$IS_MUTED" = "yes" ]; then
    color="#ff0000"
fi

printf "<span color='%s'>%s%s</span>\n" "$color" "$LABEL" "$NOW"
