#!/usr/bin/env sh
cs() {
    cd "$@" || return
    ls -lAh
}

whichkey() {
    xev | awk -F'[ )]+' '/^KeyPress/ { a[NR+2] } NR in a { printf "%-3s %s\n", $5, $8 }'
}

alias sudo='sudo '

alias ls='ls --color=auto -h1'
alias ll='ls --color=auto -lhG'
alias la='ls --color=auto -AlhG'

alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias diff='diff --color=auto'
alias dmesg='dmesg --color=auto'
alias lsip="ip a | grep -E '\<inet\>'"

alias g='git'
alias gs='git status'
alias gc='git commit'
alias gco='git checkout'
alias gcb='git checkout -b'
alias gpull='git pull'
alias gpush='git push'
alias gp='git push'
alias gpu='git push --set-upstream origin'
alias gpf='git push --force-with-lease'
alias gd='git diff'
alias gl='git log'
alias glo='git log --oneline'
alias ga='git add'
alias gca='git commit -a'
alias gsub='git submodule'
alias gsubf='git submodule foreach'
alias grt='git remote'
alias gdiff='git difftool'
alias gmt='git mergetool'
alias gmerge='git merge'
alias gm='git merge'
alias grebase='git rebase'
alias gr='git rebase'
alias gri='git rebase -i'
alias grix='git rebase -i -x'
alias grx='git rebase -i -x'
alias grt='git restore'
alias gclone='git clone'
alias gstash='git stash'
alias gsp='git stash pop'
alias gsd='git stash drop'
alias gsl='git stash list'
alias gbranch='git branch'
alias gb='git branch'
alias gclean='git branch --merged | egrep -v "(^\*|master|dev|develop|main)" | xargs -n1 -r git branch -d'
alias gw='git switch'
alias gwc='git switch -C'
alias gf='git fetch'
alias gfetch='git fetch'
alias gfa='git fetch --all'

alias sys='systemctl'
alias ssys='sudo systemctl'
alias sysu='systemctl --user'
alias sst='systemctl status'

alias please='sudo !!'
alias rtfm='man'
alias gimme='sudo chown $USER:$(id -gn $USER)'
alias free='free -h'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias mkdir='mkdir -p'
alias du='du -h'
alias df='df -h'
alias visudo='sudo -E visudo'
alias pacdiff='sudo -E pacdiff'
alias se='sudo -E '
alias bc='bc -lq'

alias pacopt='comm -13 <(pacman -Qqdt | sort) <(pacman -Qqdtt | sort)'
alias pacinstalled='comm -23 <(pacman -Qeq | sort) <(pacman -Qgq base-devel | sort)'

alias curl='curl -L --create-dirs -C -'
alias ipecho='curl ipecho.net/plain; echo'
alias xclip="xclip -selection clipboard -f"
alias countframes='ffprobe -v error -select_streams v:0 -show_entries stream=nb_frames -of default=nokey=1:noprint_wrappers=1'

alias cpr='rsync --archive -hh --partial --info=stats1 --info=progress2 --modify-window=1'
alias mvr='rsync --archive -hh --partial --info=stats1 --info=progress2 --modify-window=1 --remove-source-files'
alias sub='subliminal download -l en'
alias ports='sudo ss -tupn'
alias c='clear'

alias n='nvim'
alias ns='nvim -S'
alias ndiff='nvim -d'
alias nd='nvim -d'
alias nview='nvim -R'
alias nv='nvim -R'
alias ngit='nvim +G'
alias ng='nvim +G'

alias python='python3'
alias pip='pip3'
alias p3='python3'
alias py='python3'
alias p='python3'
alias p2='python2'

alias ta='tmux new-session -A'
alias tas='tmux new-session -A -s'

alias qr='qrencode -t UTF8'

alias nj='ninja -C build'
alias ncmake='cmake -G Ninja -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_INSTALL_PREFIX=build/install -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -CMAKE_EXPORT_COMPILE_COMMANDS=ON -B build'
alias cmake-llvm='cmake -G Ninja -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_INSTALL_PREFIX=build/install -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DLLVM_CCACHE_BUILD=ON -DLLVM_ENABLE_DOXYGEN=ON -DLLVM_USE_LINKER=lld -DLLVM_OPTIMIZED_TABLEGEN=ON -DLLVM_APPEND_VC_REV=OFF -DPW_ENABLE_WERROR=ON -C pwanalyzer/cmake/caches/Debug.cmake -B build llvm'
