#!/usr/bin/env sh

alias sudo='sudo '

alias ls='ls --color=auto'
alias ll='ls -lhG'
alias la='ls -AlhG'

alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

alias g='git'
alias gs='git status'
alias gc='git commit'
alias gco='git checkout'
alias gpull='git pull'
alias gpush='git push'
alias gd='git diff'
alias glog='git log'
alias gl='git log --oneline --decorate --all --graph'
alias ga='git add'
alias gca='git commit -a'
alias gsub='git submodule'
alias gsubf='git submodule foreach'
alias grt='git remote'
alias gdiff='git difftool'
alias gmt='git mergetool'
alias gmerge='git merge'
alias grm='git rebase'
alias gclone='git clone'
alias gz='git stash'
alias gzp='git stash pop'

alias sys='sudo systemctl'
alias sysu='systemctl --user'

alias please='sudo !!'
alias rtfm='man'
alias gimme='sudo chown $USER:$(id -gn $USER)'
alias free='free -h'
alias ...='cd ../..'
alias ....='cd ../../..'
alias mkdir='mkdir -p'
alias du='du -h'
alias df='df -h'
alias visudo='sudo -E visudo'
alias se='se'

alias pacopt='comm -13 <(pacman -Qqdt | sort) <(pacman -Qqdtt | sort)'
alias pacinstalled='comm -23 <(pacman -Qeq | sort) <(pacman -Qgq base-devel | sort)'
alias mirrorupdate='sudo reflector --country Spain --country Portugal --country France --latest 20 --age 24 --protocol https --sort rate --save /etc/pacman.d/mirrorlist; sudo rm -f /etc/pacman.d/mirrorlist.pacnew'

alias curl='curl -L --create-dirs -C -'
alias ipecho='curl ipecho.net/plain; echo'
alias ccat='pygmentize'
alias copy="xclip -selection clipboard; xclip -selection clipboard -o"
alias countframes='ffprobe -v error -select_streams v:0 -show_entries stream=nb_frames -of default=nokey=1:noprint_wrappers=1'

alias cpr='rsync --archive -hh --partial --info=stats1 --info=progress2 --modify-window=1'
alias mvr='rsync --archive -hh --partial --info=stats1 --info=progress2 --modify-window=1 --remove-source-files'
alias sub='subliminal download -l en'
alias ports='ss -atun'

alias n='nvim'
alias ns='nvim -S'
alias ndiff='nvim -d'
alias nview='nvim -R'
alias ngit='nvim +G'

alias v='vim'

alias python='python3'
alias pip='pip3'
alias p3='python3'
alias py='python3'
alias p2='python2'

alias ta='tmux new-session -Ad -s'

alias cpa='bin/camop -M "tcp://127.0.0.1:7779" -B "tcp://127.0.0.1:5533" -P "tcp://127.0.0.1:8086" -S "." -c /tmp/test.json  -m'
