#!/usr/bin/env sh
# If not running interactively, don't do anything
case $- in
    *i*) stty -ixon
        ;;
      *) return
          ;;
esac

# shellcheck source=/dev/null
[ -r  ~/.config/sh/envrc ] && . ~/.config/sh/envrc

cs() {
    cd "$@" || return
    ls -lAh
}

_fzf_compgen_path() {
  eval "$FZF_DEFAULT_COMMAND" "$1"
}

safesource "$XDG_CONFIG_HOME"/sh/aliases

# numlock
tput smkx

if [ -z "$TMUX" ] && [ -n "$SSH_TTY" ]; then
    exists tmux && exec tmux new-session -A -s ssh
fi

PS1="[\$?]\$ "
export PS1
