#!/usr/bin/env sh
# xinitrc file, used by all X sessions started by xinit (startx)

# shellcheck source=/dev/null
[ -r  ~/.config/X11/xprofile ] && . ~/.config/X11/xprofile &
if [ "$(uname -n)" != "tau" ]; then
    launch-polybar &
    sxhkd ~/.config/sxhkd/bspwm-sxhkdrc &
    exec bspwm
fi
