#!/usr/bin/env sh
# shellcheck source=/dev/null
[ -r  ~/.config/sh/envrc ] && . ~/.config/sh/envrc
systemctl --user import-environment PATH DISPLAY XAUTHORITY

display-setup

[ -r ~/.config/X11/Xresources ] && xrdb ~/.config/X11/Xresources

xsetroot -cursor_name left_ptr &
# feh --bg-center --no-fehbg ~/dotfiles/wallpapers/arch.png &
launch-polybar &
sxhkd ~/.config/sxhkd/bspwm-sxhkdrc &
input-setup &
dunst &
